#!/usr/bin/env bash

set -e

if [[ "$1" == "-i" ]]; then
    sudo podman build docker -t qmk
fi

sudo podman run \
    --rm \
    --privileged \
    -v /dev/bus/usb:/dev/bus/usb \
    -v "$(pwd)/src:/qmk_firmware/keyboards/ergodox_ez/keymaps/custom:ro" \
    localhost/qmk \
    qmk flash -kb ergodox_ez -km custom
