#include QMK_KEYBOARD_H

#define COMBO_COUNT 4
#define LT_COUNT 3
#define MT_COUNT 7

#include "engine.c"
#include "custom.c"

Combo combos[COMBO_COUNT] = {
    { KC_X, KC_J, KC_CIRC },
    { KC_X, KC_K, KC_DLR },
    { KC_X, KC_U, KC_AMPR },
    { KC_X, KC_I, KC_PIPE },
};

LayerTap layer_taps[LT_COUNT] = {
    { 2, KC_MINS },
    { 3, KC_SLSH },
    { 5, XXXXXXX },
};

ModTap mod_taps[MT_COUNT] = {
    { KC_LSFT, KC_ESC },
    { KC_RSFT, KC_ENTER },
    { KC_LCTL, KC_TAB },
    { KC_RCTL, XXXXXXX },
    { KC_RALT, KC_LGUI },
    { KC_LALT, KC_PSCR },
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_ergodox_80(
        KC_DEL,  KC_LBRC, KC_RBRC, KC_EXLM, KC_QUES, XXXXXXX, XXXXXXX,
        MT(2),   KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_HOME,
        MT(0),   KC_A,    KC_S,    KC_D,    KC_F,    KC_G,
        LT(1),   KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_END,
        XXXXXXX, XXXXXXX, KC_CAPS, MT(5),   KC_SPC,

                    XXXXXXX,       XXXXXXX,
        C(KC_LALT), C(S(KC_LALT)), KC_BRIU,
        TG(4),      C(KC_LSFT),    KC_BRID,

        XXXXXXX, XXXXXXX, KC_AT, KC_SCLN, KC_LPRN, KC_RPRN, KC_BSPC,
        KC_PGUP, KC_Y,    KC_U,  KC_I,    KC_O,    KC_P,    MT(3),
                 KC_H,    KC_J,  KC_K,    KC_L,    KC_QUOT, MT(1),
        KC_PGDN, KC_N,    KC_M,  KC_COMM, KC_DOT,  KC_GRV,  KC_BSLS,
                          LT(0), MT(4),   KC_CAPS, XXXXXXX, TG(1),

        KC_MUTE, XXXXXXX,
        KC_VOLU, C(S(KC_LALT)), C(KC_LALT),
        KC_VOLD, C(KC_LSFT),    LT(2)
    ),

    [1] = LAYOUT_ergodox_80(
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,

                 XXXXXXX, XXXXXXX,
        XXXXXXX, RESET,   XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX,

        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
                 XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
                          XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_TRNS,

        XXXXXXX, XXXXXXX,
        XXXXXXX, RESET,   XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX
    ),

    [2] = LAYOUT_ergodox_80(
        XXXXXXX,   S(KC_SCLN), KC_PEQL, KC_SPC,  XXXXXXX, XXXXXXX, XXXXXXX,
        CK_ARROW2, KC_1,       KC_2,    KC_3,    KC_PPLS, XXXXXXX, XXXXXXX,
        CK_ARROW,  KC_4,       KC_5,    KC_6,    KC_PMNS, XXXXXXX,
        XXXXXXX,   KC_7,       KC_8,    KC_9,    KC_PAST, KC_PSLS, XXXXXXX,
        XXXXXXX,   XXXXXXX,    XXXXXXX, XXXXXXX, KC_0,

                 XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX,

        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, KC_HASH, KC_PERC, XXXXXXX, XXXXXXX, XXXXXXX,
                 XXXXXXX, KC_ASTR, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
                          KC_TRNS, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,

        XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX
    ),

    [3] = LAYOUT_ergodox_80(
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, KC_LSFT, KC_LALT, XXXXXXX, XXXXXXX,
        KC_TRNS, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_LCTL,

                 XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX,

        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_LCBR, KC_RCBR, XXXXXXX,
        XXXXXXX, _______, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
                 KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT, _______, XXXXXXX,
        XXXXXXX, _______, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
                          XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,

        XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX
    ),

    [4] = LAYOUT_ergodox_80(
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, KC_WH_U, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, KC_WH_L, KC_WH_D, KC_WH_R, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, KC_LALT, KC_LCTL, KC_LSFT, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, KC_ACL0, KC_ACL2, KC_ACL1,

                 XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX,
        KC_TRNS, XXXXXXX, XXXXXXX,

        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
                 KC_MS_L, KC_MS_D, KC_MS_U, KC_MS_R, XXXXXXX, XXXXXXX,
        XXXXXXX, KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT, XXXXXXX, XXXXXXX,
                          KC_BTN2, KC_BTN3, XXXXXXX, XXXXXXX, XXXXXXX,

        XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, KC_BTN1
    ),

    [5] = LAYOUT_ergodox_80(
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   XXXXXXX,
        XXXXXXX, KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,
        XXXXXXX, KC_F11,  KC_F12,  KC_F13,  KC_F14,  KC_F15,  XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,

                 XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX,

        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
                 XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
                          XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,

        XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, KC_TRNS
    ),
};

void matrix_scan_user(void) {
    if (host_keyboard_leds() & (1 << USB_LED_CAPS_LOCK)) {
        ergodox_right_led_1_on();
    } else {
        ergodox_right_led_1_off();
    }

    if (biton32(layer_state) == 4) {
        ergodox_right_led_2_on();
    } else {
        ergodox_right_led_2_off();
    }

    if (biton32(layer_state) == 1) {
        ergodox_right_led_3_on();
    } else {
        ergodox_right_led_3_off();
    }
}
